output_dir: "./outputs/laugh"
train_data:
  video_path: "data/laugh.mp4"
  prompt: "A white man is laughing."
  n_sample_frames: 8
validation_data:
  prompts:
  - "A white man wearing sunglasses is laughing."
  video_length: 8
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 300
trainable_modules:
  - "attn_temp"
  - "s_lstm_"
  - "out_"
checkpointing_steps: 1000
validation_steps: 300